
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Mar 19 16:38:34 EDT 2014
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int DISP = 9;
  public static final int REGISTER = 19;
  public static final int INT = 20;
  public static final int RPAREN = 16;
  public static final int BEQ = 12;
  public static final int RAND = 8;
  public static final int LPAREN = 15;
  public static final int JUMPTARGET = 18;
  public static final int SUB = 3;
  public static final int LB = 14;
  public static final int COMMA = 7;
  public static final int JUMP = 11;
  public static final int EOF = 0;
  public static final int ADD = 2;
  public static final int error = 1;
  public static final int HALT = 10;
  public static final int XOR = 6;
  public static final int SB = 13;
  public static final int ADDI = 4;
  public static final int LABEL = 17;
  public static final int SLT = 5;
}

