
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Apr 04 23:18:19 EDT 2014
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int LBRACKET = 10;
  public static final int EQUALS = 19;
  public static final int LPAREN = 2;
  public static final int INT = 6;
  public static final int PRINTLN = 21;
  public static final int MINUS = 17;
  public static final int STATIC = 29;
  public static final int RPAREN = 3;
  public static final int NOT = 4;
  public static final int SEMICOLON = 20;
  public static final int AND = 13;
  public static final int LESSTHAN = 14;
  public static final int COMMA = 12;
  public static final int CLASS = 35;
  public static final int PLUS = 16;
  public static final int MAIN = 31;
  public static final int IF = 23;
  public static final int THIS = 7;
  public static final int DOT = 15;
  public static final int EOF = 0;
  public static final int BOOLEAN = 26;
  public static final int RETURN = 28;
  public static final int RBRACKET = 11;
  public static final int TRUE = 8;
  public static final int NEW = 5;
  public static final int error = 1;
  public static final int VOID = 30;
  public static final int INTLITERAL = 37;
  public static final int TIMES = 18;
  public static final int ELSE = 36;
  public static final int LBRACE = 24;
  public static final int WHILE = 22;
  public static final int PUBLIC = 27;
  public static final int RBRACE = 25;
  public static final int EXTENDS = 33;
  public static final int STRING = 32;
  public static final int FALSE = 9;
  public static final int LENGTH = 34;
  public static final int IDENTIFIER = 38;
}

